sudo: required
services:
  - docker

before_install:
  - docker build -t sekchaitanya88/fraud-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sekchaitanya88/fraud-test npm test -- --coverage

after_success:
  - docker build -t sekchaitanya88/fraud-client ./client
  - docker build -t sekchaitanya88/fraud-nginx ./nginx
  - docker build -t sekchaitanya88/fraud-server ./server 

# Log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
- docker push sekchaitanya88/fraud-client
- docker push sekchaitanya88/fraud-server
- docker push sekchaitanya88/fraud-nginx