version: '3'
services: 
  mongo:
    container_name: mongo
    image: mongo
    expose:
      - "27018"
    command: mongod --port 27018
    ports:
      - '27018:27018'     
  api:
    container_name: api
    restart: always    
    build: 
      context: ./server
      dockerfile: Dockerfile.dev    
    expose:
      - "5050"
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - MONGO_HOST=mongo
      - MONGO_PORT=27018
      - MONGO_DB=FraudDB     
    ports:
      - "5050:5050"
    links:
      - mongo  
    volumes:
      - ./server:/usr/src/app/server      
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    